version: "3.3"
services:
  app:
    build:
      context: ./
      dockerfile: src/WebUI/Dockerfile
    environment:
      - ConnectionStrings__NorthwindDatabase=Server=sqlserver;Database=NorthwindTraders;User Id=sa;Password=Password12!;MultipleActiveResultSets=true;Application Name=NorthwindTraders;
    ports:
      - "80:80"
      - "433:433"
    depends_on: 
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password12!
    ports:
      - 1434:1433